apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: vault
  targetNamespace: vault
  # install:
  #   createNamespace: true
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: vault
      chart: vault
      interval: 5m0s
  values:
    injector:
      enabled: false
    csi:
      enabled: true