---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress
  namespace: ingress
spec:
  interval: 5m0s
  releaseName: ingress
  targetNamespace: ingress
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: test-charts
      chart: ingress
      version: 0.0.5
      interval: 5m0s