---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  install:
    createNamespace: true
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: jetstack
      chart: cert-manager
      interval: 5m0s
  values:
    installCRDs: true