---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: prometheus
  targetNamespace: prometheus
  # install:
  #   createNamespace: true
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      chart: prometheus
      interval: 5m0s