---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  # install:
  #   createNamespace: true
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      chart: ingress-nginx
      interval: 5m0s