---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: private-ca
  namespace: private-ca
spec:
  interval: 5m0s
  releaseName: private-ca
  targetNamespace: private-ca
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: test-charts
      chart: private-ca
      version: 0.0.4
      interval: 5m0s