---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: grafana
  targetNamespace: grafana
  # install:
  #   createNamespace: true
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: grafana
      chart: grafana
      interval: 5m0s
  values:
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local/
      - name: Loki
        type: loki
        url: http://loki-stack.grafana.svc.cluster.local/
    # dashboardsConfigMaps: