---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - helm-repository.yml
  - grafana.yml
  - loki-stack.yml
#  - loki-distributed.yml
#  - promtail.yml
configMapGenerator:
- name: grafana-dashboard-overview
  files:
  - kubernetes.json=grafana-dashboard-overview.json