---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: promtail
  targetNamespace: grafana
  # install:
  #   createNamespace: true
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: grafana
      chart: promtail
      interval: 5m0s
  values:
    config:
      logLevel: info
      serverPort: 3101
      clients:
        - url: http://loki-distributed-distributor.grafana.svc.cluster.local:3100/loki/api/v1/push