apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: external-secrets
  targetNamespace: external-secrets
  # install:
  #   createNamespace: true
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      chart: external-secrets
      interval: 5m0s