apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: secrets-store-csi-driver
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts