apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-csi-driver
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: secrets-store-csi-driver
  targetNamespace: secrets-store-csi-driver
  # install:
  #   createNamespace: true
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: secrets-store-csi-driver
      chart: secrets-store-csi-driver
      interval: 5m0s
  values:
    syncSecret:
      enabled: true  # allows k8s secrets to be created
    enableSecretRotation: true  # watches source for updates and applies them to mounted k8s volume/secret