---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets
  namespace: secrets
spec:
  interval: 5m0s
  releaseName: secrets
  targetNamespace: secrets
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: test-charts
      chart: secrets
      version: 0.0.1
      interval: 5m0s