---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trust
  namespace: trust
spec:
  dependsOn:
    - name: private-ca
      namespace: private-ca
  interval: 5m0s
  releaseName: trust
  targetNamespace: trust
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: test-charts
      chart: trust
      version: 0.0.1
      interval: 5m0s