---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: observability
  namespace: observability
spec:
  interval: 5m0s
  releaseName: observability
  targetNamespace: observability
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: test-charts
      chart: observability
      version: 0.0.4
      interval: 5m0s